#if TOOLS
#nullable enable annotations
using System;
using System.Collections.Generic;

namespace SystemExplorer.CodeService.Autocomplete.Styling;

internal static class AutocompleteGodotTypeIconNameMap
{
	private static readonly IReadOnlyDictionary<string, string> Aliases =
		new Dictionary<string, string>(StringComparer.Ordinal)
		{
			["Aabb"] = "AABB",
			["AesContext"] = "AESContext",
			["AudioStreamWav"] = "AudioStreamWAV",
			["AudioServerInstance"] = "AudioServer",
			["Bitmap"] = "BitMap",
			["CameraServerInstance"] = "CameraServer",
			["ClassDBInstance"] = "ClassDB",
			["Colors"] = "Color",
			["Ccdik3D"] = "CCDIK3D",
			["CpuParticles2D"] = "CPUParticles2D",
			["CpuParticles3D"] = "CPUParticles3D",
			["CsgBox3D"] = "CSGBox3D",
			["CsgCombiner3D"] = "CSGCombiner3D",
			["CsgCylinder3D"] = "CSGCylinder3D",
			["CsgMesh3D"] = "CSGMesh3D",
			["CsgPolygon3D"] = "CSGPolygon3D",
			["CsgPrimitive3D"] = "CSGPrimitive3D",
			["CsgShape3D"] = "CSGShape3D",
			["CsgSphere3D"] = "CSGSphere3D",
			["CsgTorus3D"] = "CSGTorus3D",
			["CurveXyzTexture"] = "CurveXYZTexture",
			["DpiTexture"] = "DPITexture",
			["DisplayServerInstance"] = "DisplayServer",
			["DtlsServer"] = "DTLSServer",
			["EditorExportPlatformIos"] = "EditorExportPlatformIOS",
			["EditorExportPlatformLinuxBsd"] = "EditorExportPlatformLinuxBSD",
			["EditorSceneFormatImporterFbx2Gltf"] = "EditorSceneFormatImporterFBX2GLTF",
			["EditorSceneFormatImporterGltf"] = "EditorSceneFormatImporterGLTF",
			["EditorSceneFormatImporterUfbx"] = "EditorSceneFormatImporterUFBX",
			["EditorVcsInterface"] = "EditorVCSInterface",
			["EncodedObjectAsId"] = "EncodedObjectAsID",
			["EngineDebuggerInstance"] = "EngineDebugger",
			["EngineInstance"] = "Engine",
			["Fabrik3D"] = "FABRIK3D",
			["FbxDocument"] = "FBXDocument",
			["FbxState"] = "FBXState",
			["GDExtensionManagerInstance"] = "GDExtensionManager",
			["Geometry2DInstance"] = "Geometry2D",
			["Geometry3DInstance"] = "Geometry3D",
			["GltfAccessor"] = "GLTFAccessor",
			["GltfAnimation"] = "GLTFAnimation",
			["GltfBufferView"] = "GLTFBufferView",
			["GltfCamera"] = "GLTFCamera",
			["GltfDocument"] = "GLTFDocument",
			["GltfDocumentExtension"] = "GLTFDocumentExtension",
			["GltfDocumentExtensionConvertImporterMesh"] = "GLTFDocumentExtensionConvertImporterMesh",
			["GltfLight"] = "GLTFLight",
			["GltfMesh"] = "GLTFMesh",
			["GltfNode"] = "GLTFNode",
			["GltfObjectModelProperty"] = "GLTFObjectModelProperty",
			["GltfPhysicsBody"] = "GLTFPhysicsBody",
			["GltfPhysicsShape"] = "GLTFPhysicsShape",
			["GltfSkeleton"] = "GLTFSkeleton",
			["GltfSkin"] = "GLTFSkin",
			["GltfSpecGloss"] = "GLTFSpecGloss",
			["GltfState"] = "GLTFState",
			["GltfTexture"] = "GLTFTexture",
			["GltfTextureSampler"] = "GLTFTextureSampler",
			["GpuParticles2D"] = "GPUParticles2D",
			["GpuParticles3D"] = "GPUParticles3D",
			["GpuParticlesAttractor3D"] = "GPUParticlesAttractor3D",
			["GpuParticlesAttractorBox3D"] = "GPUParticlesAttractorBox3D",
			["GpuParticlesAttractorSphere3D"] = "GPUParticlesAttractorSphere3D",
			["GpuParticlesAttractorVectorField3D"] = "GPUParticlesAttractorVectorField3D",
			["GpuParticlesCollision3D"] = "GPUParticlesCollision3D",
			["GpuParticlesCollisionBox3D"] = "GPUParticlesCollisionBox3D",
			["GpuParticlesCollisionHeightField3D"] = "GPUParticlesCollisionHeightField3D",
			["GpuParticlesCollisionSdf3D"] = "GPUParticlesCollisionSDF3D",
			["GpuParticlesCollisionSphere3D"] = "GPUParticlesCollisionSphere3D",
			["Generic6DofJoint3D"] = "Generic6DOFJoint3D",
			["HmacContext"] = "HMACContext",
			["HttpClient"] = "HTTPClient",
			["HttpRequest"] = "HTTPRequest",
			["InputEventMidi"] = "InputEventMIDI",
			["InputInstance"] = "Input",
			["InputMapInstance"] = "InputMap",
			["IPInstance"] = "IP",
			["JniSingleton"] = "JNISingleton",
			["JavaClassWrapperInstance"] = "JavaClassWrapper",
			["JavaScriptBridgeInstance"] = "JavaScriptBridge",
			["Json"] = "JSON",
			["JsonRpc"] = "JSONRPC",
			["MultiplayerApi"] = "MultiplayerAPI",
			["MultiplayerApiExtension"] = "MultiplayerAPIExtension",
			["MarshallsInstance"] = "Marshalls",
			["NativeMenuInstance"] = "NativeMenu",
			["NavigationMeshGeneratorInstance"] = "NavigationMeshGenerator",
			["NavigationServer2DInstance"] = "NavigationServer2D",
			["NavigationServer2DManagerInstance"] = "NavigationServer2DManager",
			["NavigationServer3DInstance"] = "NavigationServer3D",
			["NavigationServer3DManagerInstance"] = "NavigationServer3DManager",
			["OrmMaterial3D"] = "ORMMaterial3D",
			["GodotObject"] = "Object",
			["OpenXRApiExtension"] = "OpenXRAPIExtension",
			["OpenXripBindingModifier"] = "OpenXRIPBindingModifier",
			["OSInstance"] = "OS",
			["PckPacker"] = "PCKPacker",
			["PacketPeerDtls"] = "PacketPeerDTLS",
			["PacketPeerUdp"] = "PacketPeerUDP",
			["PerformanceInstance"] = "Performance",
			["PhysicsServer2DInstance"] = "PhysicsServer2D",
			["PhysicsServer2DManagerInstance"] = "PhysicsServer2DManager",
			["PhysicsServer3DInstance"] = "PhysicsServer3D",
			["PhysicsServer3DManagerInstance"] = "PhysicsServer3DManager",
			["ProjectSettingsInstance"] = "ProjectSettings",
			["RDShaderSpirV"] = "RDShaderSPIRV",
			["Rid"] = "RID",
			["Rect2I"] = "Rect2i",
			["RenderingServerInstance"] = "RenderingServer",
			["ResourceLoaderInstance"] = "ResourceLoader",
			["ResourceImporterCsvTranslation"] = "ResourceImporterCSVTranslation",
			["ResourceImporterObj"] = "ResourceImporterOBJ",
			["ResourceImporterSvg"] = "ResourceImporterSVG",
			["ResourceImporterWav"] = "ResourceImporterWAV",
			["ResourceSaverInstance"] = "ResourceSaver",
			["ResourceUid"] = "ResourceUID",
			["ResourceUidInstance"] = "ResourceUID",
			["SkeletonModification2DCcdik"] = "SkeletonModification2DCCDIK",
			["SkeletonModification2DFabrik"] = "SkeletonModification2DFABRIK",
			["SkeletonModification3DCcdik"] = "SkeletonModification3DCCDIK",
			["SkeletonModification3DFabrik"] = "SkeletonModification3DFABRIK",
			["StreamPeerGZip"] = "StreamPeerGZIP",
			["StreamPeerTcp"] = "StreamPeerTCP",
			["StreamPeerTls"] = "StreamPeerTLS",
			["StreamPeerUds"] = "StreamPeerUDS",
			["TcpServer"] = "TCPServer",
			["TextServerManagerInstance"] = "TextServerManager",
			["ThemeDBInstance"] = "ThemeDB",
			["TimeInstance"] = "Time",
			["TranslationServerInstance"] = "TranslationServer",
			["TlsOptions"] = "TLSOptions",
			["Texture2Drd"] = "Texture2DRD",
			["Texture3Drd"] = "Texture3DRD",
			["GodotThread"] = "Thread",
			["UdpServer"] = "UDPServer",
			["UdsServer"] = "UDSServer",
			["Upnp"] = "UPNP",
			["UpnpDevice"] = "UPNPDevice",
			["Vector2I"] = "Vector2i",
			["Vector3I"] = "Vector3i",
			["Vector4I"] = "Vector4i",
			["VisualShaderNodeCurveXyzTexture"] = "VisualShaderNodeCurveXYZTexture",
			["VisualShaderNodeSdfRaymarch"] = "VisualShaderNodeSDFRaymarch",
			["VisualShaderNodeSdfToScreenUV"] = "VisualShaderNodeSDFToScreenUV",
			["VisualShaderNodeScreenUVToSdf"] = "VisualShaderNodeScreenUVToSDF",
			["VisualShaderNodeTextureSdf"] = "VisualShaderNodeTextureSDF",
			["VisualShaderNodeTextureSdfNormal"] = "VisualShaderNodeTextureSDFNormal",
			["WebRtcDataChannel"] = "WebRTCDataChannel",
			["WebRtcDataChannelExtension"] = "WebRTCDataChannelExtension",
			["WebRtcMultiplayerPeer"] = "WebRTCMultiplayerPeer",
			["WebRtcPeerConnection"] = "WebRTCPeerConnection",
			["WebRtcPeerConnectionExtension"] = "WebRTCPeerConnectionExtension",
			["WorkerThreadPoolInstance"] = "WorkerThreadPool",
			["XRServerInstance"] = "XRServer",
			["XmlParser"] = "XMLParser",
			["Xrvrs"] = "XRVRS",
			["ZipPacker"] = "ZIPPacker",
			["ZipReader"] = "ZIPReader",
		};

	internal static string ResolveNativeName(string csharpTypeName)
	{
		if (string.IsNullOrEmpty(csharpTypeName))
			return csharpTypeName ?? "";

		return Aliases.TryGetValue(csharpTypeName, out string? nativeName)
			? nativeName
			: csharpTypeName;
	}
}
#endif
